# Generated by Django 5.1.15 on 2026-06-24 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='beneficiario',
            field=models.ForeignKey(blank=True, help_text='Vacío = reserva para uno mismo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='spaces.campus'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='spaces.parkingspace'),
        ),
    ]
