# Generated by Django 5.1.15 on 2026-06-25 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_vehicle_color_alter_vehicle_marca_and_more'),
    ]

    operations = [
    ]
