# Generated by Django 5.1.15 on 2026-06-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('horario_operacion', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
                'db_table': 'campus',
            },
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(help_text='Negativo para sótanos, e.g. -2 para Sótano 2')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='spaces.campus')),
            ],
            options={
                'db_table': 'parking_lots',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='e.g. A-01', max_length=10)),
                ('tipo', models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('bicicleta', 'Bicicleta'), ('discapacitado', 'Discapacitado'), ('reservado', 'Reservado')], default='auto', max_length=15)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado'), ('mantenimiento', 'Mantenimiento')], default='libre', max_length=15)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='spaces.parkinglot')),
            ],
            options={
                'db_table': 'parking_spaces',
                'unique_together': {('lot', 'numero')},
            },
        ),
    ]
