# Generated by Django 5.1.15 on 2026-07-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_update_spaces_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='horario_operacion',
            field=models.JSONField(default=dict, help_text='Horarios por tipo de día: {lunes_sabado: {inicio, fin}, domingo: {inicio, fin}}'),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='numero',
            field=models.CharField(help_text='Ej: A-01, MOTO-05', max_length=10),
        ),
    ]
