# Generated by Django 5.1.15 on 2026-06-24 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('spaces', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], max_length=15)),
            ],
            options={
                'db_table': 'violation_types',
                'ordering': ['nivel', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='SanctionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_falta', models.CharField(choices=[('leve', 'Leve'), ('grave', 'Grave'), ('muy_grave', 'Muy Grave')], max_length=15)),
                ('numero_reincidencia', models.PositiveSmallIntegerField(help_text='1 = primera vez, 2 = segunda vez, 3 = tercera vez')),
                ('tipo_sancion', models.CharField(choices=[('advertencia', 'Advertencia (email)'), ('suspension_temporal', 'Suspensión temporal'), ('suspension_definitiva', 'Suspensión definitiva')], max_length=30)),
                ('duracion_meses', models.PositiveSmallIntegerField(blank=True, help_text='Null para advertencia o suspensión definitiva', null=True)),
            ],
            options={
                'db_table': 'sanction_rules',
                'ordering': ['nivel_falta', 'numero_reincidencia'],
                'unique_together': {('nivel_falta', 'numero_reincidencia')},
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('evidencia_foto', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('anulada', 'Anulada'), ('apelada', 'Apelada')], default='pendiente', max_length=15)),
                ('access_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='violations', to='access.accessrecord')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='spaces.campus')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_violations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='users.vehicle')),
                ('tipo_falta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='violations', to='violations.violationtype')),
            ],
            options={
                'db_table': 'violations',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('advertencia', 'Advertencia (email)'), ('suspension_temporal', 'Suspensión temporal'), ('suspension_definitiva', 'Suspensión definitiva')], max_length=30)),
                ('inicio', models.DateField(blank=True, null=True)),
                ('fin', models.DateField(blank=True, help_text='Null para suspensión definitiva', null=True)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cumplida', 'Cumplida'), ('anulada', 'Anulada'), ('apelada', 'Apelada')], default='activa', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aplicada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_sanctions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions', to=settings.AUTH_USER_MODEL)),
                ('violation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sanction', to='violations.violation')),
            ],
            options={
                'db_table': 'sanctions',
                'ordering': ['-created_at'],
            },
        ),
    ]
