# Generated by Django 5.1.15 on 2026-06-24 22:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedQRToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=64, unique=True)),
                ('user_id', models.IntegerField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'used_qr_tokens',
            },
        ),
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('salida_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado')], default='activo', max_length=15)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_records', to='spaces.campus')),
            ],
            options={
                'db_table': 'access_records',
                'ordering': ['-entrada_at'],
            },
        ),
    ]
