# Generated by Django 5.1.15 on 2026-06-24 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('spaces', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_access_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_records', to='spaces.parkingspace'),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_records', to='users.vehicle'),
        ),
    ]
