# Generated by Django 5.1.15 on 2026-07-01 05:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_fix_accessrecord_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedqrtoken',
            name='used_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
