/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/access/entry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["access_entry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/exit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["access_exit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/exit/sync/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["access_exit_sync_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/history/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["access_history_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/access/qr/entry/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["access_qr_entry_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campus_list"];
        put?: never;
        post: operations["campus_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/{campus_pk}/lots/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campus_lots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/{campus_pk}/lots/{lot_pk}/spaces/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campus_lots_spaces_list"];
        put?: never;
        post: operations["campus_lots_spaces_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/{campus_pk}/lots/{lot_pk}/spaces/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campus_lots_spaces_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["campus_lots_spaces_partial_update"];
        trace?: never;
    };
    "/api/v1/campus/{campus_pk}/lots/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campus_lots_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/{campus_pk}/occupancy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campus_occupancy_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/campus/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["campus_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["campus_partial_update"];
        trace?: never;
    };
    "/api/v1/reports/occupancy/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reports_occupancy_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reports_users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/violations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reports_violations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reservations_list"];
        put?: never;
        post: operations["reservations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["reservations_retrieve"];
        put?: never;
        post?: never;
        delete: operations["reservations_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_list"];
        put?: never;
        post: operations["users_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_retrieve"];
        put: operations["users_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_partial_update"];
        trace?: never;
    };
    "/api/v1/users/{user_pk}/vehicles/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_vehicles_list"];
        put?: never;
        post: operations["users_vehicles_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_pk}/vehicles/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["users_vehicles_partial_update"];
        trace?: never;
    };
    "/api/v1/users/import/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users_import_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/violations/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["violations_list"];
        put?: never;
        post: operations["violations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/violations/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["violations_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/violations/{id}/annul/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["violations_annul_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/violations/{id}/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["violations_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/violations/my/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["violations_my_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Campus: {
            readonly id: number;
            nombre: string;
            ciudad: string;
            direccion: string;
            /** @description Horarios por tipo de día: {lunes_sabado: {inicio, fin}, domingo: {inicio, fin}} */
            horario_operacion?: unknown;
            activo?: boolean;
            readonly lots: components["schemas"]["ParkingLot"][];
        };
        CampusList: {
            readonly id: number;
            nombre: string;
            ciudad: string;
            activo?: boolean;
        };
        /**
         * @description * `activo` - Activo
         *     * `suspendido` - Suspendido
         *     * `inactivo` - Inactivo
         * @enum {string}
         */
        Estado094Enum: "activo" | "suspendido" | "inactivo";
        ParkingLot: {
            readonly id: number;
            nombre: string;
            /** @description Número de nivel (negativo para sótanos, ej: -2) */
            nivel: number;
            readonly spaces_count: string;
            readonly free_count: string;
        };
        ParkingSpace: {
            readonly id: number;
            /** @description Ej: A-01, MOTO-05 */
            numero: string;
            tipo: components["schemas"]["ParkingSpaceTipoEnum"];
            readonly estado: components["schemas"]["ParkingSpaceEstadoEnum"];
        };
        /**
         * @description * `libre` - Libre
         *     * `ocupado` - Ocupado
         *     * `reservado` - Reservado
         *     * `mantenimiento` - Mantenimiento
         * @enum {string}
         */
        ParkingSpaceEstadoEnum: "libre" | "ocupado" | "reservado" | "mantenimiento";
        /**
         * @description * `auto` - Auto
         *     * `moto` - Moto
         *     * `bicicleta` - Bicicleta
         *     * `discapacitado` - Discapacitado
         *     * `reservado` - Reservado
         * @enum {string}
         */
        ParkingSpaceTipoEnum: "auto" | "moto" | "bicicleta" | "discapacitado" | "reservado";
        PatchedCampus: {
            readonly id?: number;
            nombre?: string;
            ciudad?: string;
            direccion?: string;
            /** @description Horarios por tipo de día: {lunes_sabado: {inicio, fin}, domingo: {inicio, fin}} */
            horario_operacion?: unknown;
            activo?: boolean;
            readonly lots?: components["schemas"]["ParkingLot"][];
        };
        PatchedParkingSpace: {
            readonly id?: number;
            /** @description Ej: A-01, MOTO-05 */
            numero?: string;
            tipo?: components["schemas"]["ParkingSpaceTipoEnum"];
            readonly estado?: components["schemas"]["ParkingSpaceEstadoEnum"];
        };
        PatchedUserUpdate: {
            /** Format: email */
            email?: string;
            nombre?: string;
            apellido?: string;
            rol?: components["schemas"]["RolEnum"];
            campus_asignado?: number | null;
            estado?: components["schemas"]["Estado094Enum"];
            /** Format: date */
            suspension_hasta?: string | null;
        };
        PatchedVehicle: {
            readonly id?: number;
            placa?: string;
            tipo?: components["schemas"]["VehicleTipoEnum"];
            marca?: string;
            modelo?: string;
            color?: string;
            activo?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        Reservation: {
            readonly id: number;
            space: number;
            readonly space_numero: string;
            readonly reservado_por: number;
            readonly reservado_por_nombre: string;
            /** @description Vacío = reserva para uno mismo. */
            beneficiario?: number | null;
            readonly beneficiario_nombre: string;
            readonly campus: number;
            /** Format: date-time */
            inicio: string;
            /** Format: date-time */
            fin: string;
            motivo: string;
            readonly estado: components["schemas"]["ReservationEstadoEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `activa` - Activa
         *     * `vencida` - Vencida
         *     * `cancelada` - Cancelada
         * @enum {string}
         */
        ReservationEstadoEnum: "activa" | "vencida" | "cancelada";
        /**
         * @description * `rector` - Rector
         *     * `director` - Director
         *     * `jefe_operaciones` - Jefe de Operaciones
         *     * `jefe_seguridad` - Jefe de Seguridad
         *     * `asistente_operaciones` - Asistente de Operaciones
         *     * `agente_seguridad` - Agente de Seguridad
         *     * `administrativo` - Administrativo
         *     * `academico` - Académico
         *     * `alumno` - Alumno
         * @enum {string}
         */
        RolEnum: "rector" | "director" | "jefe_operaciones" | "jefe_seguridad" | "asistente_operaciones" | "agente_seguridad" | "administrativo" | "academico" | "alumno";
        User: {
            readonly id: number;
            codigo_institucional: string;
            /** Format: email */
            email: string;
            nombre: string;
            apellido: string;
            rol: components["schemas"]["RolEnum"];
            readonly campus_id: number;
            readonly campus_nombre: string;
            estado?: components["schemas"]["Estado094Enum"];
            /** Format: date */
            suspension_hasta?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        UserCreate: {
            codigo_institucional: string;
            /** Format: email */
            email: string;
            nombre: string;
            apellido: string;
            rol: components["schemas"]["RolEnum"];
            campus_asignado?: number | null;
            password: string;
        };
        UserUpdate: {
            /** Format: email */
            email: string;
            nombre: string;
            apellido: string;
            rol: components["schemas"]["RolEnum"];
            campus_asignado?: number | null;
            estado?: components["schemas"]["Estado094Enum"];
            /** Format: date */
            suspension_hasta?: string | null;
        };
        Vehicle: {
            readonly id: number;
            placa: string;
            tipo: components["schemas"]["VehicleTipoEnum"];
            marca?: string;
            modelo?: string;
            color?: string;
            activo?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `auto` - Auto
         *     * `moto` - Moto
         *     * `bicicleta` - Bicicleta
         * @enum {string}
         */
        VehicleTipoEnum: "auto" | "moto" | "bicicleta";
        Violation: {
            readonly id: number;
            user: number;
            vehicle?: number | null;
            campus: number;
            readonly tipo_falta_codigo: string;
            readonly tipo_falta_nivel: string;
            descripcion: string;
            /** Format: date-time */
            fecha?: string;
            estado?: components["schemas"]["ViolationEstadoEnum"];
            readonly registrado_por_nombre: string;
            readonly sancion_propuesta: string;
        };
        /**
         * @description * `pendiente` - Pendiente
         *     * `confirmada` - Confirmada
         *     * `anulada` - Anulada
         *     * `apelada` - Apelada
         * @enum {string}
         */
        ViolationEstadoEnum: "pendiente" | "confirmada" | "anulada" | "apelada";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    access_entry_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    access_exit_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    access_exit_sync_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    access_history_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    access_qr_entry_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    campus_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampusList"][];
                };
            };
        };
    };
    campus_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Campus"];
                "application/x-www-form-urlencoded": components["schemas"]["Campus"];
                "multipart/form-data": components["schemas"]["Campus"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campus"];
                };
            };
        };
    };
    campus_lots_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campus_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingLot"][];
                };
            };
        };
    };
    campus_lots_spaces_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campus_pk: number;
                lot_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingSpace"][];
                };
            };
        };
    };
    campus_lots_spaces_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campus_pk: number;
                lot_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParkingSpace"];
                "application/x-www-form-urlencoded": components["schemas"]["ParkingSpace"];
                "multipart/form-data": components["schemas"]["ParkingSpace"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingSpace"];
                };
            };
        };
    };
    campus_lots_spaces_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campus_pk: number;
                id: number;
                lot_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingSpace"];
                };
            };
        };
    };
    campus_lots_spaces_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campus_pk: number;
                id: number;
                lot_pk: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedParkingSpace"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedParkingSpace"];
                "multipart/form-data": components["schemas"]["PatchedParkingSpace"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingSpace"];
                };
            };
        };
    };
    campus_lots_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campus_pk: number;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParkingLot"];
                };
            };
        };
    };
    campus_occupancy_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campus_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    campus_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campus"];
                };
            };
        };
    };
    campus_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCampus"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCampus"];
                "multipart/form-data": components["schemas"]["PatchedCampus"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campus"];
                };
            };
        };
    };
    reports_occupancy_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reports_users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reports_violations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reservations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"][];
                };
            };
        };
    };
    reservations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reservation"];
                "application/x-www-form-urlencoded": components["schemas"]["Reservation"];
                "multipart/form-data": components["schemas"]["Reservation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    reservations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    reservations_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    users_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["UserCreate"];
                "multipart/form-data": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreate"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    users_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["UserUpdate"];
                "multipart/form-data": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
        };
    };
    users_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserUpdate"];
                "multipart/form-data": components["schemas"]["PatchedUserUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserUpdate"];
                };
            };
        };
    };
    users_vehicles_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                };
            };
        };
    };
    users_vehicles_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Vehicle"];
                "application/x-www-form-urlencoded": components["schemas"]["Vehicle"];
                "multipart/form-data": components["schemas"]["Vehicle"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
        };
    };
    users_vehicles_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                user_pk: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedVehicle"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedVehicle"];
                "multipart/form-data": components["schemas"]["PatchedVehicle"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"];
                };
            };
        };
    };
    users_import_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    users_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    violations_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Violation"][];
                };
            };
        };
    };
    violations_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Violation"];
                "application/x-www-form-urlencoded": components["schemas"]["Violation"];
                "multipart/form-data": components["schemas"]["Violation"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Violation"];
                };
            };
        };
    };
    violations_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Violation"];
                };
            };
        };
    };
    violations_annul_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Violation"];
                "application/x-www-form-urlencoded": components["schemas"]["Violation"];
                "multipart/form-data": components["schemas"]["Violation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Violation"];
                };
            };
        };
    };
    violations_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Violation"];
                "application/x-www-form-urlencoded": components["schemas"]["Violation"];
                "multipart/form-data": components["schemas"]["Violation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Violation"];
                };
            };
        };
    };
    violations_my_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
